### ISSUE TITLE
Implement "/token" endpoint for Secure Token Service

### ISSUE THREAD

**Issue by borisrizov-zf** [eclipse-tractusx/managed-identity-wallet#139]
## Summary

This is a breakdown of the SI token task
part of task #134

## Reference

[non-normative api spec](https://github.com/eclipse-tractusx/identity-trust/blob/main/specifications/M1/identity.protocol.base.md#41-self-issued-id-token-contents)
[secure token service specification](https://github.com/eclipse-tractusx/identity-trust/blob/main/specifications/M1/identity.protocol.base.md)

## Details:

The participant must prepare an access token as a signed JWT and put it in the `access_token` claim of a self-issued token..

The participant receiving a self-issued token must unwrap it, extract the value in the `access_token` claim and use the same method to issue a self-issued token.

In both cases the "/token" endpoint is used to receive a self-issued token.

## Acceptance criteria

The MIW will provide a `POST` endpoint, path = "/token". The endpoint will accept the following parameters:

- `access_token` OPTIONAL
- `audience` REQUIRED
- `bearer_access_alias` OPTIONAL
- `bearer_access_scope` OPTIONAL
- `client_id` REQUIRED
- `client_secret` REQUIRED
- `grant_type` REQUIRED = `client_credentials`

Example token contents for the self-issued token and the access token can be found here:
https://github.com/eclipse-edc/Connector/tree/main/extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-embedded

The business logic of the "/token" endpoint uses the default key pair of the participant to sign the JWT being returned.

The business logic will NOT verify the contents of the provided `access_token`.

The business logic will return a response containing the encoded JWT self-issued token in a parameter called `access_token` - this is to ensure that the API is compliant with the OAuth2 client credentials flow and response structure, [reference docs](https://datatracker.ietf.org/doc/html/rfc9068#section-2.2-2.8), the "/token" response will also contain the `expires_in` and `token_type` fields.

**Comment by mustafasalfiti** [comment]
@borisrizov-zf  could you assign this issue to me ?

**Comment by borisrizov-zf** [comment]
@m-gora just tagging you so you have a reference to the issue.

**Comment by m-gora** [comment]
After some discussions we came up with a desired architecture for the /token endpoint:

- We want to start facilitating the hexagonal architecture style to make the MIW independent from outer influences (so we can isolate breaking changes easier)
  - Infrastructure level implementations for the token service are isolated in an adapter (in our case SSI Lib, Spring Data and the RestController)
- The /token endpoint uses the keypair from the MIW to mint the token
  - as there are only 1 key pair per wallet so far, selecting the keypair is rather trivial so far
- In order to fulfil the spec regarding the /token API we need to validate the sent credentials (as the flow is inspired by the oauth client credentials flow). However we don't want to do this in the controller, but in a custom filter that only applies to the /token endpoint

scope of this ticket encircled in red:
![Image](https://github.com/eclipse-tractusx/managed-identity-wallet/assets/3631418/daabb947-6f97-426b-a76e-6e687b768bb3)

I started drafting the architecture in code in this draft PR: #179

**Comment by OSchlienz** [comment]
https://github.com/eclipse-tractusx/identity-trust/blob/main/specifications/testing/credentialservice.md#verifyingvalidating-incoming-si-token-requests

**Comment by borisrizov-zf** [comment]
We've decided to extract the business logic from the original PR and implement in the existing arch, as time is short and we have to get this feature out for testing.
